[wpmlbridge-94] Replace old WPML autoloader with simple require
OnTheGoSystems/WPML-MU-Domain-Mapping pull request #2
Opened 2017-06-21 19:29 UTC by strategio

I took the opportunity to adjust the unit tests. I removed some unrelated tests and adjusted the existing ones to run with `WP_Mock`.

2017-06-21 20:47 UTC, sciamannikoo commented
@strategio this PR is impossible to review. 

199 changes: really?

Only to fix a very simple bug?

2017-06-21 20:49 UTC, andreasciamanna requested changes
@strategio this PR is impossible to review. 

199 changes: really?

Only to fix a very simple bug?

Please:
- Create a PR only for the specific issue and try to not get tempted to rewrite everything again
- If you want to refactor, write tests, move files around, each of these things should be part of a separated commit

2017-06-21 20:49 UTC, sciamannikoo commented on changelog.md
> +#1.0.1
@strategio  Since the type of change, I think is worth pushing to 1.1.0.

2017-06-21 20:49 UTC, sciamannikoo commented on composer.json
> +  "description": "WPML ST Dependencies",
@strategio  maybe change this description?

2017-06-21 20:49 UTC, sciamannikoo commented on composer.json
> +  "name": "wpml/mu-domain-mapping",
@strategio please use "otgs/wpml-mu-domain-mapping"

2017-06-21 20:49 UTC, sciamannikoo commented on plugin.php
> +Version: 1.0.1
@strategio same here about the version number

2017-06-21 20:49 UTC, sciamannikoo commented on plugin.php
> +	require_once 'classes/class-wpml-mu-domain-mapping-filters.php';
@strategio Don't we use autoloading?

2017-06-21 20:49 UTC, sciamannikoo commented on plugin.php
>  require_once 'classes/class-wpml-mu-domain-mapping-requirements.php';
@strategio Don't we use autoloading?

2017-06-22 15:38 UTC, strategio commented on plugin.php
> +	require_once 'classes/class-wpml-mu-domain-mapping-filters.php';
@sciamannikoo we agreed to avoid using composer for non-dev, so they can just download and install it on their site out-of-the-box.

2017-06-22 15:39 UTC, strategio commented
@sciamannikoo, I changed the version to 1.1.0.

We have an old ticket *wpmlbridge-63* that I'll use to open a PR for the tests cleanup and update.

2017-06-22 15:43 UTC, sciamannikoo commented on plugin.php
> +	require_once 'classes/class-wpml-mu-domain-mapping-filters.php';
Right

2017-06-22 15:45 UTC, andreasciamanna approved these changes
It looks good to me, now.

2017-06-30 15:20 UTC, dimitrismitsis commented
@sciamannikoo Could you please merge this? I don't have write access :)

2017-06-30 15:27 UTC, strategio commented
I will do this @dimitrismitsis

2017-06-30 15:27 UTC, merged