Add support for domain-mapping plugin from WPMUDEV
OnTheGoSystems/WPML-MU-Domain-Mapping pull request #5
Opened 2018-03-12 11:54 UTC by dgwatkins

Comes from compsupp-2737

2018-03-12 12:13 UTC, strategio reviewed
@dgwatkins, it looks good to me. I didn't know these 2 plugins were sharing table names at this point. It looks like one is the fork of the other...

Concerning the version, I suggest to change it later to include the 2 fixes and then tag the branch.

2018-03-12 12:13 UTC, strategio commented on changelog.md
> +#1.1.1
@dgwatkins, I have another fix waiting for approval (https://github.com/OnTheGoSystems/WPML-MU-Domain-Mapping/pull/4). So I suggest that we bump the version later when the 2 fixes are merged. Could you please remove this?

2018-03-12 12:13 UTC, strategio commented on plugin.php
> +Version: 1.1.1
Same here, please keep the current version number.

2018-03-12 12:50 UTC, dgwatkins commented
@strategio There it is, thanks

2018-11-07 12:58 UTC, andreasciamanna requested changes

2018-11-07 12:58 UTC, andreasciamanna commented on classes/class-wpml-mu-domain-mapping-requirements.php
> +		if ( $this->is_plugin_active_for_network( 'domain-mapping/domain-mapping.php' ) ) {
@dgwatkins as usual, the plugin folder might not be what we expect, even for must-use plugins.

What about checking if the `Domainmap_Plugin` class exists instead?

2018-11-09 13:23 UTC, dgwatkins commented on classes/class-wpml-mu-domain-mapping-requirements.php
> +		if ( $this->is_plugin_active_for_network( 'domain-mapping/domain-mapping.php' ) ) {
The reason is:

1) This plugin acts as a bridge for 2 different plugins
2) We check for the other one this way
3) So I checked this one in the same way

I can make the change to both though ..

2018-11-09 13:27 UTC, dgwatkins commented on classes/class-wpml-mu-domain-mapping-requirements.php
> +		if ( $this->is_plugin_active_for_network( 'domain-mapping/domain-mapping.php' ) ) {
@andreasciamanna Sorry, I don't think I should change anything

We are not just checking if the plugin is active in the current site, we are checking if its active in the network.

And I can't figure that out just by the existence of a class

2018-11-09 13:28 UTC, dgwatkins commented on changelog.md
> +#1.1.1
removed ages ago, but forgot to resolve the discussion

2018-11-09 13:28 UTC, dgwatkins commented on plugin.php
> +Version: 1.1.1
same here

2018-11-09 13:57 UTC, andreasciamanna approved these changes

2018-11-09 14:01 UTC, dgwatkins commented
What do you think @strategio ?
Are we ready to merge this and release ?
Let me know anything else you need from me

2018-12-07 11:00 UTC, andreasciamanna submitted a review, later dismissed

2018-12-07 11:11 UTC, strategio commented
Oh sorry @dgwatkins, I completely missed your request. It's fine to me! Maybe we should add a tag for this change. What do you think @andreasciamanna?

2018-12-07 11:12 UTC, strategio submitted a review, later dismissed

2018-12-07 11:13 UTC, andreasciamanna commented
@strategio What sort of tag? And where it should be added?

2018-12-07 11:14 UTC, strategio commented
For the changelog @andreasciamanna https://github.com/OnTheGoSystems/WPML-MU-Domain-Mapping/blob/40e3fe61aad24b08a65d900ff759406d17ebb042/changelog.md.

2018-12-07 13:51 UTC, andreasciamanna commented
@strategio you mean to release a new version, therefore **to tag **this project, not to "add a tag".

I thought you were talking about GitHub labels (aka tags):
![image](https://user-images.githubusercontent.com/181780/49651371-42726400-fa2f-11e8-9a0e-ec99f42865db.png)

Sure, this project is a rarely updated project: a new version is fine.

By the way, I don't know who's the maintainer or owner of this project, neither I know who usually publishes the updates.

2018-12-07 20:26 UTC, strategio commented
@dgwatkins, I didn't notice that your PR comes from a fork. I wanted to remove your last "FIXUP" commit and reword your main commit, but I can't.

Could you please do this? (the version in the second commit is fine).

You can also reword the first commit like this:

>     Add support for domain-mapping plugin from WPMUDEV
> 
>     https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-2737

Then we can merge it.

2018-12-10 17:47 UTC, dgwatkins commented
@strategio All set

2018-12-10 19:55 UTC, strategio approved these changes

2018-12-10 19:56 UTC, strategio commented
@andreasciamanna, could you please add your approval again?

2018-12-10 20:29 UTC, andreasciamanna approved these changes

2018-12-10 23:35 UTC, merged